site_name: 自动测试建模开发手册
nav:
    - 概述: index.md
    - 动作原语: actions.md
    - ETestUSB 引擎API: api_usb.md
    - ETestRT 引擎API: api_rt.md
    - ETestLite 引擎API: api_lua.md
    - 接口配置: interface.md
    - 协议配置: protocol.md
theme: readthedocs